#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

fail() {
  printf 'error: %s\n' "$1" >&2
  exit 1
}

info() {
  printf '[media-audit] %s\n' "$1"
}

command -v python3 >/dev/null 2>&1 || fail "python3 is required to generate a strong password"
command -v id >/dev/null 2>&1 || fail "id is required to detect the local VM user"

[[ ! -e ".env" ]] || fail ".env already exists; review it manually instead of overwriting it"

PASSWORD="$(
  python3 - <<'PY'
import secrets

print(secrets.token_urlsafe(24))
PY
)"

[[ -n "${PASSWORD}" ]] || fail "password generation failed"

HOST_UID="$(id -u)"
HOST_GID="$(id -g)"

umask 077
cat > ".env" <<EOF
# Generated by scripts/debian-vm-init-env.sh
# Default access is local-only. For LAN access, set MEDIA_AUDIT_BIND=0.0.0.0
# only behind a VM firewall, VPN, or another controlled administration path.
MEDIA_AUDIT_BIND=127.0.0.1
MEDIA_AUDIT_PORT=8080
MEDIA_AUDIT_UID=${HOST_UID}
MEDIA_AUDIT_GID=${HOST_GID}
MEDIA_AUDIT_REQUIRE_AUTH=true
MEDIA_AUDIT_WEB_USERNAME=admin
MEDIA_AUDIT_WEB_PASSWORD=${PASSWORD}
EOF
chmod 600 ".env"

info ".env created with local-only bind and web authentication enabled"
info "store MEDIA_AUDIT_WEB_PASSWORD from .env in the maintenance password vault before customer use"
